# Generated by Django 4.1.3 on 2022-11-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_count', models.IntegerField(default=0)),
                ('project_keys', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('preview_link', models.CharField(max_length=500)),
                ('description_link', models.CharField(max_length=500)),
                ('code_link', models.CharField(max_length=500)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsAdmin.projectgroup')),
            ],
        ),
    ]
