# Generated by Django 4.1.3 on 2022-11-02 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsAdmin', '0002_project_create_date_projectgroup_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 12, 45, 55, 351049, tzinfo=datetime.timezone.utc), verbose_name='date-created'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 12, 45, 55, 312602, tzinfo=datetime.timezone.utc), verbose_name='date-created'),
        ),
    ]
